name: Hourly Volatility Notifier

on:
  schedule:
    - cron: '0 * * * *'   # every hour (UTC)
  workflow_dispatch: {}

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: python volatility_bot.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          MODE: ${{ secrets.MODE }}
          TOP_N: ${{ secrets.TOP_N }}
          MIN_VOLUME_USD: ${{ secrets.MIN_VOLUME_USD }}
          MIN_QUOTE_VOL_USDT: ${{ secrets.MIN_QUOTE_VOL_USDT }}
